### PR TITLE
Updates to support current Reek version

### PR DESCRIPTION
**Pull request by blelump**
Hello, I'd like to provide a PR:

update to support current Reek version

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
Thanks @blelump . I don't use this tool any more so I'll just merge. Hopefully it works.

**Comment by blelump** [comment]
@sauliusgrigaitis , thanks! May I ask why have you abandoned it ?

**Comment by sauliusgrigaitis** [comment]
We use Jenkins with Violations plugin and Reek XML output. That's the only convenient way I found to reliably get noticed about newly introduced Reek violations.

**Comment by blelump** [comment]
That's clever! Actually we're using Jenkins as well, but I haven't heard of `Violation` plugin. Thanks for mentioning it. I've found `reek-git` useful, because it works pretty similar to `rubocop-git`, which allow to run checks against single commit.

**Comment by sauliusgrigaitis** [comment]
All those diff based tools (reek-git, rubocop-git, pronto etc.) can detect only some of the violations. The only reliable way I found to detect all the newly introduced violations is to diff full violations reports between commits. Jenkins `Violations` plugin does exactly that.

**Comment by blelump** [comment]
@sauliusgrigaitis , thanks for clarification!

All these `*-git` libraries will indeed report only violations that come from particular commit and obviously some of them may be omitted. Especially when you run Reek on a changed file, where only one line is changed and just for this one line Reek will not complain (because the context is a single line). However, if you'd run Reek on the whole file, it would indeed report more smells, because now the context is much broader (the whole file), which might be helpful as we don't have a plan to use Reek as an oracle (more like a code review helper, where the reviewer decide whether a smell is valid in given context). Good point though!

**Pull request merged**
